### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by sl1200mk2** [Pancho63/Diluz#1]
hello,
sur l'IRC j'ai demandé à aroom d'essayer d'étoffer le readMe avec un howto step by step d'installation de l'environnement de compilation pour pouvoir compiler/déployer sur iPhone D::Luz

++

**Comment by Pancho63** [comment]
good idea..
m si ça veut dire : créer un compte développeur, installer Xcode et Qtcreator…
Pas sûr que ça s’adresse au lambda..

et je lui laisse le plaisir de répondre aux divers « ça marche pas »…

++

**Comment by aroom** [comment]
ben voilà, pancho à déjà fait tout le travail :)

**Comment by Pancho63** [comment]
J’ai pas compris ??

**Comment by aroom** [comment]
ben t'as déjà énuméré la marche à suivre dans ton message précédent ;)

**Comment by Pancho63** [comment]
ya qq même un peu plus à faire…
notamment l’import du git dans QtCreator + nos échanges sur IRC pour faire reconnaitre l’Iphone…
si tu as un Howto précis, j’ai 1 ou 2 potes qui devraient pouvoir faire de bon cobbaye (pas passionnés d’informatique + ont un Iphone)

**Comment by aroom** [comment]
évidemment. je blaque.

je suis dessus. cependant la méthode est déjà très bien documenté - mais j'ai rien trouvé en français.

**Comment by Pancho63** [comment]
cool
good luck

**Comment by Pancho63** [comment]
et sinon : un loup
si on créé un réseau avec le mac pour connecter l’iphone, celui-ci ne reçoit pas d’adresse IP,
ou elle n’est pas sur le m sous-reseau…
doit surement falloir créer une adresse ip fixe…
je regarde à l’occas’.. sauf si tu as une solution..

**Comment by sl1200mk2** [comment]
IMHO tu ferais mieux de créer une nouvelle issue pour chaque sujet différent...
++

**Comment by sl1200mk2** [comment]
tu peux me poster une .apk que je regarde si ça fait pareil sur android?

++

**Comment by Pancho63** [comment]
sur android, normalement tu peux pas te connecter au réseau créé par le mac (car réseau ad-hoc)
sauf en craquant le tel
rien de nouveau en .apk…

je crois que c seulement si le mac est pas connecté à internet

**Comment by aroom** [comment]
j'ai fait un pull request. j'espère au bon endroit

**Comment by sl1200mk2** [comment]
ok,
mais je vais voir si ça fonctionne avec un réseau créer à partir du
téléphone

++

**Comment by aroom** [comment]
yep faut créer un thread par sujet

**Comment by aroom** [comment]
@Pancho63 j'ai pas pu créer de pull request sur la branch master

**Comment by Pancho63** [comment]
chez moi ça fonctionne..

**Comment by aroom** [comment]
oui mais toi t'es le owner ?

**Comment by Pancho63** [comment]
(qd je disais que ça marche chez moi, je répondais à Nico (avec un nouveau titre de sujet..))
ben oui, t’as pas le droit…
(et c pas plutôt un push? c nouveau github pour moi)

je veux bien garder la main sur le github, du moins dans un premier temps…
passe moi le texte, je ferais un copier/coller

**Comment by aroom** [comment]
changer le sujet par mail, je crois que ça suffit pas. faut créer une nouvelle issue, via git.

concernant le pull resquest :  dans pull resquest, ya "request", du coup tu va voir ce qui a changé du code et tu l'accepte ou non. la en l'occurrence j'ai juste édité le readme.md. je crois pas que quiconque puisse modifier le code sans que tu lui donne ton autorisation.

je crois que c'est comme ça que ça fonctionne. mais Nico connais mieux que moi

**Comment by Pancho63** [comment]
cool !!
je vois l'idée,
Super fonctionnement!
mais pas de pull request, ici...

**Comment by aroom** [comment]
ben non, j'ai pas l'authorisation. est-ce que tu aurais bloqué cette fonction?

**Comment by Pancho63** [comment]
non, j'ai rien désactivé...
mais rien activé non plus...
je regarde de mon côté

**Comment by sl1200mk2** [comment]
au regard de la connexion de D::Luz,
si le téléphone créer un réseau, et que l'ordi est connecté à ce réseau, ça
ne fonctionne pas non plus...

++

**Comment by Pancho63** [comment]
j'ai eu le pull request de nico..
aroom, Il doit falloir que tu créé un fork

**Comment by Pancho63** [comment]
nico : j'ai créé une nouvelle issue pour le reseau

**Comment by aroom** [comment]
ok je crois que c'est bon

**Comment by sl1200mk2** [comment]
moi je vois pas de demande de PR de la part d'aroom sur le git de pancho...

**Comment by Pancho63** [comment]
non plus...

**Comment by aroom** [comment]
et là?

**Comment by Pancho63** [comment]
all good

**Comment by aroom** [comment]
eh bé

**Comment by Pancho63** [comment]
je te cite en fin de texte, qd m !!

**Comment by aroom** [comment]
bon c'est une version de base. je vous laisse corriger les fautes d'orthographe hein... 

pourquoi pas envoyer un de tes cobayes au casse pipe voir ou il bloque. pour se faire une idée.

**Comment by Pancho63** [comment]
j'en contacte 2..

**Comment by Pancho63** [comment]
messages envoyés..
