### ISSUE TITLE
reseau local

### ISSUE THREAD

**Issue by Pancho63** [Pancho63/Diluz#3]
chez moi ça marche
je créé un point d'accès ds mon tel
j'y connect l'ordi
tutto bene..

t'as redémarré l'OSC de DLight?

**Comment by sl1200mk2** [comment]
ben ouais mais dans D::Luz, comme adresse IP ya écrit
10.x.x.x
je suis primairement connecté en 4G, le tel créer un réseau wifi à partir de là.
et du coup l'adresse de ma carte wifi est 192.168.x.x

**Comment by sl1200mk2** [comment]
pour préciser l'adresse 192.168.x.x est celle de la carte wifi de l'ordi

**Comment by Pancho63** [comment]
bizzare que ton ordi ne soit pas ds le m sous reseau que le tel...
tu as essayer de changer l'ip de dluz ds dluz (si il y en a plusieurs tu peux cliquer et choisir)

tu es en dhpc sur l'ordi?

**Comment by sl1200mk2** [comment]
a putain!
j'avais pas vu qu'on pouvait choisir l'IP du NIC...
attends j'essaie

**Comment by sl1200mk2** [comment]
ben ouais du coup, meme ss réseau pour les deux et là ça marche....
faut le mettre dans le readMe :-)
et du coup tu peux closer cette issue

++

**Comment by Pancho63** [comment]
oki

**Comment by sl1200mk2** [comment]
juste pour voir si ça réouvre l'erreur et pour noter ici un truc

**Comment by Pancho63** [comment]
chez moi ça s'affiche
dans les close

**Comment by sl1200mk2** [comment]
donc j'ai une config qui doit pas arriver souvent mais 
-la carte réseau de l'ordi a l'adresse 192.168.1.10
-la carte wifi à l'adresse 192.168.43.161
et diluz 192.168.43.1

quand je fais le request depuis diluz, DL renvoi l'adresse 192.168.1.10 comme son adresse de serveur (car c'est la première listé dans les NIC je crois) et enregistre 192.168.43.1

et là ça ne fonctionne pas...
si jéteins le wifi de l'ordi, ça ne fonctionne pas non plus

si j'éteins le partage de connexion, que je reconnecte diluz sur le meme reseau que l'ordi, là ça fonctionne.

chelou isn't it

**Comment by sl1200mk2** [comment]
donc il faut que dans DL je mette une option pour choisi le NIC utilisé pour l'OSC
right?

**Comment by Pancho63** [comment]
yep, ou filtrer en fonction de celle qu'envoie la téléco (il faut nécessairement être dans le m sous-réseau)

**Comment by sl1200mk2** [comment]
ça veut dire qu'il me faut deux serveur (un par NIC) et ça bof....

le sous réseau est le meme
255.255.255.0 à chaque fois

**Comment by Pancho63** [comment]
ça, c le mask
et ça veut dire que des machines ont besoin des 3 premiers paramètres identiques pour se voir sur le réseau.
ton server ne peut pas être en 127.0.0.1 ? 
ici ça marche
et du coup, toutes les entrées réseau sont re routées..
il faudrait "juste" que Dlight renvoie l'adresse ip de la machine qui ressemble à celle du request..

**Comment by sl1200mk2** [comment]
attends j'essaie

**Comment by Pancho63** [comment]
pour préciser, ici la partie server n'est pas liée à une IP, seulement un port:
udpSocket->bind( PORT, QUdpSocket::ShareAddress);

**Comment by sl1200mk2** [comment]
et QUdpSocket::ShareAddress c'est quoi?

**Comment by Pancho63** [comment]
je dirais que c si jamais une autre appli écoute le m port et la m adress..
au cas où...
udpSocket->bind( PORT)
fonctionne aussi
